# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2020 Takumi Sueda <puhitaku@gmail.com>
# (C) Copyright 2000-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

ifndef	CONFIG_SPL_BUILD
obj-y	:= pwsh6.o
else
obj-y	:= iomux.o
endif
